# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='UserTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='elections.UserType'),
        ),
    ]
