# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_profile_usertypeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowToVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ElectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
                ('UserTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.UserType')),
            ],
        ),
    ]
