# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_auto_20171109_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='CandidateReg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='VotingOpen',
            field=models.BooleanField(default=False),
        ),
    ]
