# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_auto_20171112_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeballot',
            name='CandidateID',
        ),
        migrations.RemoveField(
            model_name='completeballot',
            name='Rank',
        ),
        migrations.AddField(
            model_name='candidate',
            name='Bio',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
