# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_auto_20171129_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ProfilePicture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
