# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeballot',
            name='Vote',
            field=models.TextField(null=True),
        ),
    ]
