# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0016_auto_20180110_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='ProfilePicture',
            new_name='Poster',
        ),
    ]
