# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0017_auto_20180123_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='imageposts/')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Candidate')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
