# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0018_auto_20180130_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ProfilePicture',
            field=models.ImageField(default='default_profile.png', upload_to='imageposts/'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
    ]
