# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0021_auto_20180212_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='Complete',
            field=models.BooleanField(default=False),
        ),
    ]
