# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0022_election_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='Seats',
            field=models.IntegerField(default=7),
        ),
    ]
