# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0023_election_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='EmailConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
