# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0025_result_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Poster',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ProfilePicture',
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
