# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0026_auto_20180223_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
